<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MudBlazor"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BearCat.Core\BearCat.Core.csproj"/>
        <ProjectReference Include="..\Bearcat.Website\Bearcat.Website.csproj"/>
    </ItemGroup>
</Project>