# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/src/Bearcat.Abstractions"
      - "/src/Bearcat.Application"
      - "/src/Bearcat.Archivers"
      - "/src/Bearcat.Desktop"
      - "/src/Bearcat.Domain"
      - "/src/Bearcat.Host"
      - "/src/Bearcat.Hosters"
      - "/src/Bearcat.ImageHosters"
      - "/src/Bearcat.Infrastructure"
      - "/src/Bearcat.LinkCrypters"
      - "/src/Bearcat.NfoDatabases"
      - "/src/Bearcat.Website"
      - "/test/Bearcat.Archivers.IntegrationTest"
      - "/test/Bearcat.Domain.IntegrationTest"
      - "/test/Bearcat.Hosters.UnitTest"
      - "/test/Bearcat.ImageHosters.UnitTest"
      - "/test/Bearcat.IntegrationTest.Utils"
      - "/test/Bearcat.LinkCrypters.UnitTest"
      - "/test/Bearcat.NfoDatabases.UnitTest"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major:
        update-types:
          - "major"
    ignore:
        - dependency-name: "AngleSharp*" # hard depencency of BlazorBlueprint
          versions: [">0.17.1"]
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major:
        update-types:
          - "major"