<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bit.BlazorUI" Version="10.3.0" />
    <PackageVersion Include="Bit.BlazorUI.Assets" Version="10.3.0" />
    <PackageVersion Include="Bit.BlazorUI.Charts" Version="4.9.9" />
    <PackageVersion Include="Bit.BlazorUI.Extras" Version="10.3.0" />
    <PackageVersion Include="Bit.BlazorUI.Icons" Version="10.3.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Npgsql" Version="10.0.1" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageVersion Include="Radzen.Blazor" Version="8.4.2" />
    <PackageVersion Include="Refit" Version="8.0.0" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="8.0.0" />
    <PackageVersion Include="MudBlazor" Version="8.15.0" />
    <PackageVersion Include="AntDesign" Version="1.5.1" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2" />
    <PackageVersion Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
  </ItemGroup>
</Project>