// <auto-generated />
using System;
using Bearcat.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BearCat.Infrastructure.Migrations
{
    [DbContext(typeof(BearcatDbContext))]
    [Migration("20260110203358_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigId");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.ArchiveConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFilesBasePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArchiveNamePrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ArchivePassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArchiverFullClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ArchiveConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.ArchiveFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<string>("FullFileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.ToTable("ArchiveFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.HosterRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HosterFullClassName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("HosterRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReleaseFolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.Property<int>("OnlineState")
                        .HasColumnType("integer");

                    b.Property<int>("UploadConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("UploadState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.HasIndex("UploadConfigId");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.UploadConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("HosterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigId");

                    b.HasIndex("HosterRegistrationId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CheckedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.Property<string>("HosterFileLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OnlineState")
                        .HasColumnType("integer");

                    b.Property<int>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveFileId");

                    b.HasIndex("UploadId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Archive", b =>
                {
                    b.HasOne("Bearcat.Domain.Domain.Entities.ArchiveConfig", "ArchiveConfig")
                        .WithMany("Archives")
                        .HasForeignKey("ArchiveConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.ArchiveConfig", b =>
                {
                    b.HasOne("Bearcat.Domain.Domain.Entities.Release", "Release")
                        .WithMany("ArchiveConfigs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.ArchiveFile", b =>
                {
                    b.HasOne("Bearcat.Domain.Domain.Entities.Archive", "Archive")
                        .WithMany("ArchiveFiles")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Upload", b =>
                {
                    b.HasOne("Bearcat.Domain.Domain.Entities.Archive", "Archive")
                        .WithMany("Uploads")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bearcat.Domain.Domain.Entities.UploadConfig", "UploadConfig")
                        .WithMany("Uploads")
                        .HasForeignKey("UploadConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");

                    b.Navigation("UploadConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.UploadConfig", b =>
                {
                    b.HasOne("Bearcat.Domain.Domain.Entities.ArchiveConfig", "ArchiveConfig")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("ArchiveConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Domain.Entities.HosterRegistration", "HosterRegistration")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("HosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Domain.Entities.Release", "Release")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfig");

                    b.Navigation("HosterRegistration");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("Bearcat.Domain.Domain.Entities.ArchiveFile", "ArchiveFile")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("ArchiveFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Domain.Entities.Upload", "Upload")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveFile");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Archive", b =>
                {
                    b.Navigation("ArchiveFiles");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.ArchiveConfig", b =>
                {
                    b.Navigation("Archives");

                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.ArchiveFile", b =>
                {
                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.HosterRegistration", b =>
                {
                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Release", b =>
                {
                    b.Navigation("ArchiveConfigs");

                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.Upload", b =>
                {
                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Domain.Entities.UploadConfig", b =>
                {
                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
