<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlazorBlueprint.Components" />
        <PackageReference Include="BlazorBlueprint.Icons.Lucide" />
        <PackageReference Include="Humanizer" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bearcat.Domain\Bearcat.Domain.csproj" />
        <ProjectReference Include="..\Bearcat.Infrastructure\Bearcat.Infrastructure.csproj" />
    </ItemGroup>
</Project>
