// <auto-generated />
using System;
using System.Collections.Generic;
using Bearcat.Domain.Entities;
using Bearcat.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BearCat.Infrastructure.Migrations
{
    [DbContext(typeof(BearcatDbContext))]
    [Migration("20260522171737_AddReleaseInfos")]
    partial class AddReleaseInfos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bearcat.Domain.Entities.ApplicationConfigurationOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerializedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationKey", "PropertyName")
                        .IsUnique();

                    b.ToTable("ApplicationConfigurationOverrides");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.PrimitiveCollection<List<string>>("ErrorMessages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigId");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFilesBasePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArchiveNamePrefix")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ArchivePassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArchiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ArchiveConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfigTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFilesBasePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArchivePassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArchiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("UseReleaseNameAsArchiveName")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("ArchiveConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<string>("FullFileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.ToTable("ArchiveFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.HosterRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HosterClassName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("HosterRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.PrimitiveCollection<List<string>>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("UploadConfigLinkCrypterId")
                        .HasColumnType("integer");

                    b.Property<int>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UploadConfigLinkCrypterId");

                    b.HasIndex("UploadId");

                    b.ToTable("LinkCrypterContainers");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkCrypterClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("LinkCrypterRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.NfoDatabaseRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NfoDatabaseClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("NfoDatabaseClassName")
                        .IsUnique();

                    b.ToTable("NfoDatabaseRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<int?>("LinkCrypterContainerId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<int?>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.HasIndex("LinkCrypterContainerId");

                    b.HasIndex("UploadId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReleaseFolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseGroupId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseExternalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReleaseInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<List<ReleaseExternalInfoUrl>>("Urls")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseInfoId");

                    b.ToTable("ReleaseExternalInfos");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseFolderAutomation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FolderNamePattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("ReleaseFolderAutomations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnableAutomaticReuploads")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumberOfHoursUntilReupload")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ReleaseGroups");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NfoDatabaseClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReleaseDatabaseUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SizeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SizeUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VideoType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId", "NfoDatabaseClassName")
                        .IsUnique();

                    b.ToTable("ReleaseInfos");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReleaseGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseGroupId");

                    b.ToTable("ReleaseTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.PrimitiveCollection<List<string>>("ErrorMessages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("OnlineState")
                        .HasColumnType("integer");

                    b.Property<int>("UploadConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("UploadState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.HasIndex("UploadConfigId");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("HosterRegistrationId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("LinksDistributedTo")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigId");

                    b.HasIndex("HosterRegistrationId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LinkCrypterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UploadConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkCrypterRegistrationId");

                    b.HasIndex("UploadConfigId");

                    b.ToTable("UploadConfigLinkCrypters");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LinkCrypterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UploadConfigTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkCrypterRegistrationId");

                    b.HasIndex("UploadConfigTemplateId");

                    b.ToTable("UploadConfigLinkCrypterTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("HosterRegistrationId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("LinksDistributedTo")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigTemplateId");

                    b.HasIndex("HosterRegistrationId");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("UploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CheckedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.PrimitiveCollection<List<string>>("ErrorMessages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("HosterFileLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OnlineState")
                        .HasColumnType("integer");

                    b.Property<int>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveFileId");

                    b.HasIndex("UploadId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Archive", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveConfig", "ArchiveConfig")
                        .WithMany("Archives")
                        .HasForeignKey("ArchiveConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfig", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("ArchiveConfigs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfigTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany("ArchiveConfigTemplates")
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveFile", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Archive", "Archive")
                        .WithMany("ArchiveFiles")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainer", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.UploadConfigLinkCrypter", "UploadConfigLinkCrypter")
                        .WithMany("LinkCrypterContainers")
                        .HasForeignKey("UploadConfigLinkCrypterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.Upload", "Upload")
                        .WithMany("LinkCrypterContainers")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");

                    b.Navigation("UploadConfigLinkCrypter");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Archive", "Archive")
                        .WithMany("Notifications")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterContainer", "LinkCrypterContainer")
                        .WithMany("Notifications")
                        .HasForeignKey("LinkCrypterContainerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.Upload", "Upload")
                        .WithMany("Notifications")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Archive");

                    b.Navigation("LinkCrypterContainer");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Release", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseGroup", "ReleaseGroup")
                        .WithMany("Releases")
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseExternalInfo", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseInfo", "ReleaseInfo")
                        .WithMany("ExternalInfos")
                        .HasForeignKey("ReleaseInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseInfo");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseFolderAutomation", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany()
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseInfo", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("ReleaseInfos")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseGroup", "ReleaseGroup")
                        .WithMany()
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Upload", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Archive", "Archive")
                        .WithMany("Uploads")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bearcat.Domain.Entities.UploadConfig", "UploadConfig")
                        .WithMany("Uploads")
                        .HasForeignKey("UploadConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");

                    b.Navigation("UploadConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfig", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveConfig", "ArchiveConfig")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("ArchiveConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.HosterRegistration", "HosterRegistration")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("HosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfig");

                    b.Navigation("HosterRegistration");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypter", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterRegistration", "LinkCrypterRegistration")
                        .WithMany()
                        .HasForeignKey("LinkCrypterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.UploadConfig", "UploadConfig")
                        .WithMany("LinkCrypters")
                        .HasForeignKey("UploadConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkCrypterRegistration");

                    b.Navigation("UploadConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypterTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterRegistration", "LinkCrypterRegistration")
                        .WithMany()
                        .HasForeignKey("LinkCrypterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.UploadConfigTemplate", "UploadConfigTemplate")
                        .WithMany("LinkCrypterTemplates")
                        .HasForeignKey("UploadConfigTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkCrypterRegistration");

                    b.Navigation("UploadConfigTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveConfigTemplate", "ArchiveConfigTemplate")
                        .WithMany("UploadConfigTemplates")
                        .HasForeignKey("ArchiveConfigTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.HosterRegistration", "HosterRegistration")
                        .WithMany()
                        .HasForeignKey("HosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany("UploadConfigTemplates")
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfigTemplate");

                    b.Navigation("HosterRegistration");

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveFile", "ArchiveFile")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("ArchiveFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.Upload", "Upload")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveFile");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Archive", b =>
                {
                    b.Navigation("ArchiveFiles");

                    b.Navigation("Notifications");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfig", b =>
                {
                    b.Navigation("Archives");

                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfigTemplate", b =>
                {
                    b.Navigation("UploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveFile", b =>
                {
                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.HosterRegistration", b =>
                {
                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainer", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Release", b =>
                {
                    b.Navigation("ArchiveConfigs");

                    b.Navigation("ReleaseInfos");

                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseGroup", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseInfo", b =>
                {
                    b.Navigation("ExternalInfos");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseTemplate", b =>
                {
                    b.Navigation("ArchiveConfigTemplates");

                    b.Navigation("UploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Upload", b =>
                {
                    b.Navigation("LinkCrypterContainers");

                    b.Navigation("Notifications");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfig", b =>
                {
                    b.Navigation("LinkCrypters");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypter", b =>
                {
                    b.Navigation("LinkCrypterContainers");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigTemplate", b =>
                {
                    b.Navigation("LinkCrypterTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
