// <auto-generated />
using System;
using System.Collections.Generic;
using Bearcat.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bearcat.Infrastructure.Migrations
{
    [DbContext(typeof(BearcatDbContext))]
    [Migration("20260627155927_MakeReleaseFolderPathOptional")]
    partial class MakeReleaseFolderPathOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bearcat.Domain.Entities.ApplicationConfigurationOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerializedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationKey", "PropertyName")
                        .IsUnique();

                    b.ToTable("ApplicationConfigurationOverrides");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("ArchiveFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.PrimitiveCollection<List<string>>("ErrorMessages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigId");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFilesBasePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArchiveNamePrefix")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ArchivePassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArchiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ArchiveConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfigTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("ArchiveFilesBasePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArchivePassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArchiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("UseReleaseNameAsArchiveName")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("ArchiveConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<string>("FullFileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Md5Hash")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.ToTable("ArchiveFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.BackgroundTaskState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("DefaultInterval")
                        .HasColumnType("interval");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("IntervalOverride")
                        .HasColumnType("interval");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("LastExecutionStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastFinishedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<DateTime?>("LastStartedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("BackgroundTaskStates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.CollectionImageUploadConfigTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageHosterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageHosterRegistrationId");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("CollectionImageUploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.CollectionUploadSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedArchivePassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PasswordPolicy")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseCollectionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseCollectionId", "Key")
                        .IsUnique();

                    b.ToTable("CollectionUploadSlots");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.DistributionSiteRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DistributionSiteClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EncryptedSession")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.ToTable("DistributionSiteRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ForumPostTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ForumPostTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.HosterRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HosterClassName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxParallelUploadsOverride")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresCaptchaVerification")
                        .HasColumnType("boolean");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.ToTable("HosterRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageHosterRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageHosterClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("ImageHosterRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.PrimitiveCollection<string>("ErrorMessages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ImageUploadConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("UploadState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImageUploadConfigId");

                    b.ToTable("ImageUploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUploadConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageHosterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReleaseCollectionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageHosterRegistrationId");

                    b.HasIndex("ReleaseCollectionId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ImageUploadConfigs", t =>
                        {
                            t.HasCheckConstraint("CK_ImageUploadConfig_Owner", "(\"ReleaseId\" IS NOT NULL) <> (\"ReleaseCollectionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUploadConfigTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageHosterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageHosterRegistrationId");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("ImageUploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUploadUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageSize")
                        .HasColumnType("integer");

                    b.Property<int>("ImageUploadId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageUploadId");

                    b.ToTable("ImageUploadUrls");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollectionUploadSlotId")
                        .HasColumnType("integer");

                    b.Property<string>("ContainerUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<bool>("EnableCaptcha")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableClickAndLoad")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableContainerDownload")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<int>("LinkCrypterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("StatusImageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UploadConfigLinkCrypterId")
                        .HasColumnType("integer");

                    b.Property<int?>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionUploadSlotId");

                    b.HasIndex("LinkCrypterRegistrationId");

                    b.HasIndex("UploadConfigLinkCrypterId");

                    b.HasIndex("UploadId");

                    b.ToTable("LinkCrypterContainers");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainerSourceUpload", b =>
                {
                    b.Property<int>("LinkCrypterContainerId")
                        .HasColumnType("integer");

                    b.Property<int>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("LinkCrypterContainerId", "UploadId");

                    b.HasIndex("UploadId");

                    b.ToTable("LinkCrypterContainerSourceUploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkCrypterClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.ToTable("LinkCrypterRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.NfoDatabaseRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NfoDatabaseClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("NfoDatabaseClassName")
                        .IsUnique();

                    b.ToTable("NfoDatabaseRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<int?>("LinkCrypterContainerId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<int?>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<int?>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.HasIndex("LinkCrypterContainerId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("UploadId");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasFilter("\"ResolvedAt\" IS NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.PostedLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<int?>("ReleaseCollectionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseCollectionId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("PostedLocations", t =>
                        {
                            t.HasCheckConstraint("CK_PostedLocation_Owner", "(\"ReleaseId\" IS NOT NULL) <> (\"ReleaseCollectionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.QualityCheckRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QualityProfileId");

                    b.ToTable("QualityCheckRules");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.QualityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("QualityProfiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<DateTime?>("MediaMetadataExtractedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("QualityGateEvaluatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<int>("QualityGateState")
                        .HasColumnType("integer");

                    b.Property<int?>("ReleaseCollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseContentType")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseFolderPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleaseInfoCheckedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadsPostedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("QualityGateState");

                    b.HasIndex("ReleaseCollectionId");

                    b.HasIndex("ReleaseFolderPath");

                    b.HasIndex("ReleaseGroupId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("MetadataCheckedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReleaseContentType")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadsPostedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseGroupId", "Key")
                        .IsUnique();

                    b.ToTable("ReleaseCollections");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseCollectionMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ReleaseCollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("SeriesDatabaseClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SeriesDatabaseUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseCollectionId")
                        .IsUnique();

                    b.ToTable("ReleaseCollectionMetadata");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseExternalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReleaseInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseInfoId");

                    b.ToTable("ReleaseExternalInfos");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseFolderAutomation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FolderNamePattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("ReleaseFolderAutomations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseFolderObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("LastChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.ToTable("ReleaseFolderObservations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnableAutomaticReuploads")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumberOfHoursUntilReupload")
                        .HasColumnType("integer");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QualityProfileId");

                    b.ToTable("ReleaseGroups");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NfoDatabaseClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReleaseDatabaseUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SizeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SizeUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VideoType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId")
                        .IsUnique();

                    b.ToTable("ReleaseInfos");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseMediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MediaInfoJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MediaInfoText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ReleaseMediaFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseNfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReleaseInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseInfoId")
                        .IsUnique();

                    b.ToTable("ReleaseNfos");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseQualityIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ReleaseQualityIssues");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReleaseCollectionDetectionMode")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseCollectionKeyTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReleaseCollectionNameTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReleaseCollectionPattern")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReleaseContentType")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseGroupId");

                    b.ToTable("ReleaseTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.SeriesDatabaseRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SeriesDatabaseClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SeriesDatabaseClassName")
                        .IsUnique();

                    b.ToTable("SeriesDatabaseRegistrations");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.PrimitiveCollection<List<string>>("ErrorMessages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("OnlineState")
                        .HasColumnType("integer");

                    b.Property<bool>("PremiumOnlyDownload")
                        .HasColumnType("boolean");

                    b.Property<int>("UploadConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("UploadState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.HasIndex("UploadConfigId");

                    b.HasIndex("UploadState", "OnlineState");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("CollectionUploadSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("HosterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PremiumOnlyDownload")
                        .HasColumnType("boolean");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigId");

                    b.HasIndex("CollectionUploadSlotId");

                    b.HasIndex("HosterRegistrationId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerScope")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableCaptcha")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableClickAndLoad")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableContainerDownload")
                        .HasColumnType("boolean");

                    b.Property<int>("LinkCrypterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UploadConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkCrypterRegistrationId");

                    b.HasIndex("UploadConfigId");

                    b.ToTable("UploadConfigLinkCrypters");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerScope")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableCaptcha")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableClickAndLoad")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableContainerDownload")
                        .HasColumnType("boolean");

                    b.Property<int>("LinkCrypterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UploadConfigTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkCrypterRegistrationId");

                    b.HasIndex("UploadConfigTemplateId");

                    b.ToTable("UploadConfigLinkCrypterTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveConfigTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("CollectionUploadSlotExpectedArchivePassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("CollectionUploadSlotIsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("CollectionUploadSlotKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CollectionUploadSlotName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CollectionUploadSlotPasswordPolicy")
                        .HasColumnType("integer");

                    b.Property<int>("HosterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PremiumOnlyDownload")
                        .HasColumnType("boolean");

                    b.Property<int>("ReleaseTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveConfigTemplateId");

                    b.HasIndex("HosterRegistrationId");

                    b.HasIndex("ReleaseTemplateId");

                    b.ToTable("UploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CheckedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) without time zone");

                    b.PrimitiveCollection<List<string>>("ErrorMessages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HosterFileLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OnlineState")
                        .HasColumnType("integer");

                    b.Property<int>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveFileId");

                    b.HasIndex("UploadId");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Archive", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveConfig", "ArchiveConfig")
                        .WithMany("Archives")
                        .HasForeignKey("ArchiveConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfig", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("ArchiveConfigs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfigTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany("ArchiveConfigTemplates")
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveFile", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Archive", "Archive")
                        .WithMany("ArchiveFiles")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.CollectionImageUploadConfigTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ImageHosterRegistration", "ImageHosterRegistration")
                        .WithMany("CollectionImageUploadConfigTemplates")
                        .HasForeignKey("ImageHosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany("CollectionImageUploadConfigTemplates")
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageHosterRegistration");

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.CollectionUploadSlot", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseCollection", "ReleaseCollection")
                        .WithMany("UploadSlots")
                        .HasForeignKey("ReleaseCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseCollection");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUpload", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ImageUploadConfig", "ImageUploadConfig")
                        .WithMany("ImageUploads")
                        .HasForeignKey("ImageUploadConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageUploadConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUploadConfig", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ImageHosterRegistration", "ImageHosterRegistration")
                        .WithMany("ImageUploadConfigs")
                        .HasForeignKey("ImageHosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.ReleaseCollection", "ReleaseCollection")
                        .WithMany("ImageUploadConfigs")
                        .HasForeignKey("ReleaseCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("ImageUploadConfigs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ImageHosterRegistration");

                    b.Navigation("Release");

                    b.Navigation("ReleaseCollection");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUploadConfigTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ImageHosterRegistration", "ImageHosterRegistration")
                        .WithMany("ImageUploadConfigTemplates")
                        .HasForeignKey("ImageHosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany("ImageUploadConfigTemplates")
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageHosterRegistration");

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUploadUrl", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ImageUpload", "ImageUpload")
                        .WithMany("ImageUrls")
                        .HasForeignKey("ImageUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageUpload");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainer", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.CollectionUploadSlot", "CollectionUploadSlot")
                        .WithMany()
                        .HasForeignKey("CollectionUploadSlotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterRegistration", "LinkCrypterRegistration")
                        .WithMany()
                        .HasForeignKey("LinkCrypterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.UploadConfigLinkCrypter", "UploadConfigLinkCrypter")
                        .WithMany("LinkCrypterContainers")
                        .HasForeignKey("UploadConfigLinkCrypterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.Upload", "Upload")
                        .WithMany("LinkCrypterContainers")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CollectionUploadSlot");

                    b.Navigation("LinkCrypterRegistration");

                    b.Navigation("Upload");

                    b.Navigation("UploadConfigLinkCrypter");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainerSourceUpload", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterContainer", "LinkCrypterContainer")
                        .WithMany("SourceUploads")
                        .HasForeignKey("LinkCrypterContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.Upload", "Upload")
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkCrypterContainer");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Archive", "Archive")
                        .WithMany("Notifications")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterContainer", "LinkCrypterContainer")
                        .WithMany("Notifications")
                        .HasForeignKey("LinkCrypterContainerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("Notifications")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.Upload", "Upload")
                        .WithMany("Notifications")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Archive");

                    b.Navigation("LinkCrypterContainer");

                    b.Navigation("Release");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.PostedLocation", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseCollection", "ReleaseCollection")
                        .WithMany("PostedLocations")
                        .HasForeignKey("ReleaseCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("PostedLocations")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Release");

                    b.Navigation("ReleaseCollection");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.QualityCheckRule", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.QualityProfile", "QualityProfile")
                        .WithMany("Rules")
                        .HasForeignKey("QualityProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QualityProfile");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Release", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseCollection", "ReleaseCollection")
                        .WithMany("Releases")
                        .HasForeignKey("ReleaseCollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bearcat.Domain.Entities.ReleaseGroup", "ReleaseGroup")
                        .WithMany("Releases")
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReleaseCollection");

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseCollection", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseGroup", "ReleaseGroup")
                        .WithMany()
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseCollectionMetadata", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseCollection", "ReleaseCollection")
                        .WithOne("Metadata")
                        .HasForeignKey("Bearcat.Domain.Entities.ReleaseCollectionMetadata", "ReleaseCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseCollection");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseExternalInfo", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseInfo", "ReleaseInfo")
                        .WithMany("ExternalInfos")
                        .HasForeignKey("ReleaseInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Bearcat.Domain.Entities.ReleaseExternalInfoUrl", "Urls", b1 =>
                        {
                            b1.Property<int>("ReleaseExternalInfoId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Type")
                                .HasJsonPropertyName("type");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasJsonPropertyName("url");

                            b1.HasKey("ReleaseExternalInfoId", "__synthesizedOrdinal");

                            b1.ToTable("ReleaseExternalInfos");

                            b1
                                .ToJson("Urls")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ReleaseExternalInfoId");
                        });

                    b.Navigation("ReleaseInfo");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseFolderAutomation", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany()
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseGroup", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.QualityProfile", "QualityProfile")
                        .WithMany("ReleaseGroups")
                        .HasForeignKey("QualityProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QualityProfile");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseInfo", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithOne("ReleaseInfo")
                        .HasForeignKey("Bearcat.Domain.Entities.ReleaseInfo", "ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseMediaFile", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("MediaFiles")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseNfo", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseInfo", "ReleaseInfo")
                        .WithOne("ReleaseNfo")
                        .HasForeignKey("Bearcat.Domain.Entities.ReleaseNfo", "ReleaseInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReleaseInfo");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseQualityIssue", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("QualityIssues")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ReleaseGroup", "ReleaseGroup")
                        .WithMany()
                        .HasForeignKey("ReleaseGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReleaseGroup");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Upload", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.Archive", "Archive")
                        .WithMany("Uploads")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bearcat.Domain.Entities.UploadConfig", "UploadConfig")
                        .WithMany("Uploads")
                        .HasForeignKey("UploadConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");

                    b.Navigation("UploadConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfig", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveConfig", "ArchiveConfig")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("ArchiveConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.CollectionUploadSlot", "CollectionUploadSlot")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("CollectionUploadSlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bearcat.Domain.Entities.HosterRegistration", "HosterRegistration")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("HosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.Release", "Release")
                        .WithMany("UploadConfigs")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfig");

                    b.Navigation("CollectionUploadSlot");

                    b.Navigation("HosterRegistration");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypter", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterRegistration", "LinkCrypterRegistration")
                        .WithMany()
                        .HasForeignKey("LinkCrypterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.UploadConfig", "UploadConfig")
                        .WithMany("LinkCrypters")
                        .HasForeignKey("UploadConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkCrypterRegistration");

                    b.Navigation("UploadConfig");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypterTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.LinkCrypterRegistration", "LinkCrypterRegistration")
                        .WithMany()
                        .HasForeignKey("LinkCrypterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.UploadConfigTemplate", "UploadConfigTemplate")
                        .WithMany("LinkCrypterTemplates")
                        .HasForeignKey("UploadConfigTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkCrypterRegistration");

                    b.Navigation("UploadConfigTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigTemplate", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveConfigTemplate", "ArchiveConfigTemplate")
                        .WithMany("UploadConfigTemplates")
                        .HasForeignKey("ArchiveConfigTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.HosterRegistration", "HosterRegistration")
                        .WithMany()
                        .HasForeignKey("HosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.ReleaseTemplate", "ReleaseTemplate")
                        .WithMany("UploadConfigTemplates")
                        .HasForeignKey("ReleaseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveConfigTemplate");

                    b.Navigation("HosterRegistration");

                    b.Navigation("ReleaseTemplate");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("Bearcat.Domain.Entities.ArchiveFile", "ArchiveFile")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("ArchiveFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bearcat.Domain.Entities.Upload", "Upload")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveFile");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Archive", b =>
                {
                    b.Navigation("ArchiveFiles");

                    b.Navigation("Notifications");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfig", b =>
                {
                    b.Navigation("Archives");

                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveConfigTemplate", b =>
                {
                    b.Navigation("UploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ArchiveFile", b =>
                {
                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.CollectionUploadSlot", b =>
                {
                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.HosterRegistration", b =>
                {
                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageHosterRegistration", b =>
                {
                    b.Navigation("CollectionImageUploadConfigTemplates");

                    b.Navigation("ImageUploadConfigTemplates");

                    b.Navigation("ImageUploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUpload", b =>
                {
                    b.Navigation("ImageUrls");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ImageUploadConfig", b =>
                {
                    b.Navigation("ImageUploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.LinkCrypterContainer", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("SourceUploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.QualityProfile", b =>
                {
                    b.Navigation("ReleaseGroups");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Release", b =>
                {
                    b.Navigation("ArchiveConfigs");

                    b.Navigation("ImageUploadConfigs");

                    b.Navigation("MediaFiles");

                    b.Navigation("Notifications");

                    b.Navigation("PostedLocations");

                    b.Navigation("QualityIssues");

                    b.Navigation("ReleaseInfo");

                    b.Navigation("UploadConfigs");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseCollection", b =>
                {
                    b.Navigation("ImageUploadConfigs");

                    b.Navigation("Metadata");

                    b.Navigation("PostedLocations");

                    b.Navigation("Releases");

                    b.Navigation("UploadSlots");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseGroup", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseInfo", b =>
                {
                    b.Navigation("ExternalInfos");

                    b.Navigation("ReleaseNfo");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.ReleaseTemplate", b =>
                {
                    b.Navigation("ArchiveConfigTemplates");

                    b.Navigation("CollectionImageUploadConfigTemplates");

                    b.Navigation("ImageUploadConfigTemplates");

                    b.Navigation("UploadConfigTemplates");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.Upload", b =>
                {
                    b.Navigation("LinkCrypterContainers");

                    b.Navigation("Notifications");

                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfig", b =>
                {
                    b.Navigation("LinkCrypters");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigLinkCrypter", b =>
                {
                    b.Navigation("LinkCrypterContainers");
                });

            modelBuilder.Entity("Bearcat.Domain.Entities.UploadConfigTemplate", b =>
                {
                    b.Navigation("LinkCrypterTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
