// <auto-generated />
using System;
using System.Collections.Generic;
using BearCat.Core.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BearCat.Core.Infrastructure.Database.Migrations
{
    [DbContext(typeof(BearcatDbContext))]
    [Migration("20260104223639_LimitLengthOfArchiveNamePrefix")]
    partial class LimitLengthOfArchiveNamePrefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BearCat.Core.Domain.Entities.ArchiveUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(4)
                        .HasColumnType("timestamp(4) with time zone");

                    b.HasKey("Id");

                    b.ToTable("DistributionUploads");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveNamePrefix")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ArchivePassword")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ArchiverFullClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DistributionFolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("HosterRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetArchiveFileSizeMb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HosterRegistrationId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.DistributionArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("ArchiveFilePaths")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("ArchiveUploadId")
                        .HasColumnType("integer");

                    b.Property<int>("DistributionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveUploadId");

                    b.HasIndex("DistributionId");

                    b.ToTable("DistributionArchives");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.HosterFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchiveUploadId")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveUploadId");

                    b.ToTable("HosterFiles");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.HosterRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HosterFullClassName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerializedConfig")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("HosterRegistrations");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.Release", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.Distribution", b =>
                {
                    b.HasOne("BearCat.Core.Domain.Entities.HosterRegistration", "HosterRegistration")
                        .WithMany()
                        .HasForeignKey("HosterRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BearCat.Core.Domain.Entities.Release", "Release")
                        .WithMany("Distributions")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("HosterRegistration");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.DistributionArchive", b =>
                {
                    b.HasOne("BearCat.Core.Domain.Entities.ArchiveUpload", "ArchiveUpload")
                        .WithMany("DistributionArchives")
                        .HasForeignKey("ArchiveUploadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BearCat.Core.Domain.Entities.Distribution", "Distribution")
                        .WithMany("Archives")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ArchiveUpload");

                    b.Navigation("Distribution");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.HosterFile", b =>
                {
                    b.HasOne("BearCat.Core.Domain.Entities.ArchiveUpload", "ArchiveUpload")
                        .WithMany("HosterFiles")
                        .HasForeignKey("ArchiveUploadId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ArchiveUpload");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.ArchiveUpload", b =>
                {
                    b.Navigation("DistributionArchives");

                    b.Navigation("HosterFiles");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.Distribution", b =>
                {
                    b.Navigation("Archives");
                });

            modelBuilder.Entity("BearCat.Core.Domain.Entities.Release", b =>
                {
                    b.Navigation("Distributions");
                });
#pragma warning restore 612, 618
        }
    }
}
